project:
  type: website

website:
  title: "Paul Jackson Resume"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
  pdf:
    documentclass: report
    margin-left: 30mm
    margin-right: 30mm



