# Paul Jackson {.center-header}
::: {.contact-info}
303.889.9672 • paulr.jackson@proton.me • Remote / Denver, CO •
[linkedin.com/in/paulthegeek](https://linkedin.com/in/paulthegeek)
:::

## TECHNICAL PROJECT MANAGER/SOFTWARE ENGINEER

Product Manager with 10+ years of proven success and expertise in planning, prioritizing and developing software projects by fostering customer and stakeholder relationships and cross-functional collaboration.

## Skills and Knowledge
Agile Product Management | Product Development | Software Engineering | Agile Methodologies | Team Leadership | Cross-Functional Collaboration | Javascript | React | Vue.js | REST API | Facilitation B2B & B2C Relationships | Written and Verbal Communication | Cost Saving | Jira | Confluence | Github

## Expereince

### Blueprint Test prep, Technical Product Manager — April 2024 - Present

- Drove feature prioritization by providing strategic technical insight to Product Managers and COO across multiple product verticals, aligning roadmap decisions with engineering feasibility and business impact
- Translated complex and various stakeholder needs into actionable user stories by partnering cross-functionally with Product Managers, Education Experts, Designers, and Engineers ensuring quality, user-centered implementations that directly served student success and business goals
- Designed and launched a scalable triage workflow for customer-reported issues, streamlining intake from Support and enabling faster resolution of critical bugs resulting in improved product stability and customer satisfaction
- Co-led architectural planning for the 2.0 Study Plan platform in close collaboration with the Director of Engineering and Platform Engineering Manager, laying the foundation for scalable, flexible and future product innovation

### Posit, Pbc (Formerly Rstudio), Product Manager — Aug 2022 - Jul 2023

- Led and prioritized product decisions based on student feedback and in support of doubling enrollment from the previous year for the Academy platform and aligning with the a company OKR goal of increasing paid users for the cloud platforms
- Researched and implemented new tooling for academic data science tutorial creation based on the feedback from internal teachers. The new tooling increased tutorial and project creation by 25%
- Led the design and implementation of a new agile process within our development team. This included consistent collaborative spikes, prototyping, planning meetings, and retrospectives. This new method of developing stories increased our story output by 50% over three quarters

### Posit, Pbc, Software Engineer | Product Manager — Feb 2020 - Aug 2022
- Implemented a new subscription and billing platform for self-service the Posit Cloud product. The subscription service increased revenue by 100% as it was a free beta product previously
- Enhanced internal tooling to improve support experience allowing us to get more direct feedback from students and delegate who should handle certain issues


### Travis CI, Software Engineer — Jan 2018 - Mar 2019
- Modernized our build/deployment progress UI based on user feedback both internal and external. It resulted in users better understanding what the status of a job was which reduced support tickets by 20%
- Planned and implemented the redesign of the landing page with our designer to drive users to use the paid version of our product and make pricing tiers simpler. This resulted in increase of paid users

# Levels Beyond, Software Engineer — Jun 2016 - Aug 2017
- Designed and implemented a new workflow page for content creators based on user feedback. It resulted in a workflow that improved navigation and increased usability and efficiency
- Designed and implemented a custom viewport based on user feedback and interviews. It resulted in view that allowed for users to have the same features in the list and tile views when they would switch between

# thoughtbot, Software Engineer — Nov 2015 - Apr 2016
- Designed and implemented features in our internal tool based on feedback from teammates. The features resulted in better tracking of customers and scheduling work across the business
- Implemented an employee to employer education benefit system based on the requirements from our client Guild. This feature resulted in helping our customer have a core feature for launching their product

# iTriage(Aetna), Software Engineer — Aug 2012 - Nov 2015
- Led our front-end engineering team creating a new consumer health insurance app with collaboration between engineering, design, product, and Aetna executives. This resulted in a direct to consumer product for iOS, Android, and the Web
- Led and developed reusable web components that could be shared across the iTraige and Aetna codebases. The shared web components ensured consistency across the codebases, a consistent UI, reduced duplication, and increased stability

# Rally Software Development, Customer Success Engineer — June 2008 - Aug 2012
- Problem solving a variety of issues from tool usage, agile practices, debugging, and supporting customer code using Rally’s web service API
- Built custom solutions in Javascript, Ruby, and C# for customers using Rally’s web service API
- Built custom integrations with JIRA, HP Quality Center, and Excel
- Rotating scrum master for my team

# Education
Metropolitan State University of Denver - Bachelor of Science, Computer Science, Minor: Mathematics
  